"""empty message

Revision ID: 02d8024f5d62
Revises: ec16f6820eb9
Create Date: 2017-10-28 06:41:35.817670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d8024f5d62'
down_revision = 'ec16f6820eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'message_type')
    # ### end Alembic commands ###