"""add missing payment relationship

Revision ID: 4298d21f4116
Revises: 69a1a36d724a
Create Date: 2017-10-28 03:19:00.279832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4298d21f4116'
down_revision = '69a1a36d724a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('finished', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'finished')
    # ### end Alembic commands ###