"""empty message

Revision ID: 45d4b3145472
Revises: c36b4632b981
Create Date: 2017-10-28 11:41:37.389637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d4b3145472'
down_revision = 'c36b4632b981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###