"""empty message

Revision ID: 53eecd703c5c
Revises: dfeb429998ff
Create Date: 2017-10-28 02:34:04.750049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53eecd703c5c'
down_revision = 'dfeb429998ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('finished', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'finished')
    # ### end Alembic commands ###