"""create payment table

Revision ID: 7805f5505656
Revises: dfeb429998ff
Create Date: 2017-10-28 02:45:04.837044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7805f5505656'
down_revision = 'dfeb429998ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('goal_d', sa.Integer(), nullable=True),
    sa.Column('operation_number', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=True),
    sa.Column('operation_status', sa.String(), nullable=True),
    sa.Column('operation_amount', sa.Integer(), nullable=False),
    sa.Column('operation_currency', sa.String(), nullable=True),
    sa.Column('operation_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['goal_d'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###