"""empty message

Revision ID: 89a4a2f5dfa7
Revises: 19a15d5956bd
Create Date: 2017-10-28 05:19:46.879931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a4a2f5dfa7'
down_revision = '19a15d5956bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.drop_column('payment', 'operation_number')
    op.add_column('payment', sa.Column('operation_number', sa.String))
    op.drop_constraint('payment_goal_d_fkey', 'payment', type_='foreignkey')
    op.create_foreign_key(None, 'payment', 'goal', ['goal_id'], ['id'])
    op.drop_column('payment', 'goal_d')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('goal_d', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.create_foreign_key('payment_goal_d_fkey', 'payment', 'goal', ['goal_d'], ['id'])
    op.alter_column('payment', 'operation_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('payment', 'goal_id')
    # ### end Alembic commands ###